import { hc } from "hono/client";

import type { AppType } from "./server";

// this is a trick to calculate the type when compiling
const client = hc<AppType>("");
export type Client = typeof client;

/**
 * A fully typed client for the cannoli-server
 *
 * @param serverSecret - The server secret to use for authentication, generated by cannoli-server on first run
 * @param args - The arguments to pass to the hc function, typical hono client arguments
 * @returns A typed hono client
 * @example
 * const client = makeCannoliServerClient(serverSecret, "http://localhost:3000");
 */
export const makeCannoliServerClient = (
  serverSecret: string,
  ...args: Parameters<typeof hc>
): Client => {
  const [url, options] = [...args];
  const c = hc<AppType>(url, {
    ...options,
    headers: {
      ...options?.headers,
      Authorization: `Bearer ${serverSecret}`,
    },
  });
  return c;
};
